repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace  # Удаляет пробелы в конце строк
      - id: end-of-file-fixer     # Обеспечивает пустую строку в конце файла
      - id: mixed-line-ending     # Приводит концы строк к LF (Unix)

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8               # Проверка PEP 8

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8             # Автоматическое исправление PEP 8
        args: [--in-place, --aggressive]